spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/employees"
	username: "root"
	password: "mojetrudnehaslo"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: "update"
      naming-strategy: "org.hibernate.cfg.ImprovedNamingStrategy"
      dialtect: "org.hibernate.dialect.MySQL5Dialect"
    show-sql: "true"